services:
  app:
    build: .
    container_name: node_app
    image: nodeapp:v1
    ports:
      - "3000:8080"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: cartao_fidelidade
      DB_PORT: 3306
    networks:
      - app_net
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: cartao_fidelidade
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
    driver: bridge
